import java.sql.Date;
import java.util.Scanner;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App3 {

	public static void main(String[] args) {
		final int DEFAULT_SIZE = 20;
		int[] no = new int[DEFAULT_SIZE];
		String[] contents = new String[DEFAULT_SIZE];
		Date[] registeredDate = new Date[DEFAULT_SIZE];
		int [] hit = new int[DEFAULT_SIZE];
		int len = 0;

		Scanner keyIn = new Scanner(System.in);

		for (int i = 0; i < DEFAULT_SIZE; i++) {

			System.out.println("번호? ");
			no[i] = Integer.parseInt(keyIn.nextLine());

			System.out.print("내용? ");
			contents[i] = keyIn.nextLine();

			registeredDate[i] = new Date(System.currentTimeMillis());
		    
			hit[i] = 0;
			
			len++;

			System.out.print("계속하시곘습니까?(Y/n) ");
			String input = keyIn.nextLine();
			if (input.equalsIgnoreCase("y") || input.equals("")) {
				continue;
			}
			break;
		}

		keyIn.close();

		for (int i = 0; i < len; i++) {

			System.out.printf("%d, %s, %s, %d\n" , no[i],contents[i],registeredDate[i],hit[i]);
		
		}
	}
}
